# Workflow Configuration
name: ThanhND Backend CD Workflows

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
      
  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main

  # Scheduled trigger at 4:30 AM UTC, weekday
  schedule:
    - cron: '30 4 * * 1-5'
  
env:
  NODE_VERSION: '18.x'

jobs:
  install-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies before Test
        run:
          cd ./starter/backend &&
          python -m pip install --upgrade pip &&
          pip install pipenv && 
          pipenv install pytest --dev && 
          pipenv install --dev
      - name: Run Test
        run: cd ./starter/backend && pipenv run test

  deploy-job:
    needs: install-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: latest  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
      - name: Build Docker image
        run: |
          cd ./starter/backend
          docker build -t backend:${GITHUB_SHA} .
      - name: Tag Docker Image
        run:
          cd ./starter/backend && 
          docker tag backend:${GITHUB_SHA} ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
      - name: Push Docker image to ECR
        run:
          cd ./starter/backend && 
          docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA}
      - name: Update kebeconfig to access EKS
        run:
          aws eks update-kubeconfig --name cluster --region us-east-1
      - name: Deploy to Kubernetes
        run:
          cd ./starter/backend/k8s &&
          kustomize edit set image backend=${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/backend:${GITHUB_SHA} &&
          kustomize build | kubectl apply -f -
